# Config File for CircleCI,
# Code for tests from circleCI:
# https://circleci.com/blog/building-android-on-circleci/

#Defining Version
version: 2.1
orbs:
  android: circleci/android@3.0.1

executors:
  android-executor:
    docker:
      - image: circleci/android:latest
    resource_class: xlarge

jobs:
  unit-test:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "build.gradle" }}

  android-test:
    executor: android-executor
    parameters:
      system-image:
        type: string
        default: system-images;android-33;google_apis;x86
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-
      - run:
          name: Start Emulator and Run Tests
          command: |
            # Start the emulator with the specified system image
            echo "Starting emulator"
            ./gradlew connectedDebugAndroidTest
            # Wait for emulator to fully boot
            adb wait-for-device
            adb shell input keyevent 82
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit
            find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  release-build:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-
      - run:
          name: Assemble Release Build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "build.gradle" }}

workflows:
  build-and-test:
    jobs:
      - unit-test
      - android-test:
          filters:
            branches:
              ignore: main
      - android-test:
          name: android-test-all
          matrix:
            parameters:
              system-image:
                - system-images;android-33;google_apis;x86
                - system-images;android-32;google_apis;x86
                - system-images;android-31;google_apis;x86
                - system-images;android-30;google_apis;x86
                - system-images;android-29;google_apis;x86
          filters:
            branches:
              only: main
      - release-build:
          requires:
            - unit-test
            - android-test-all
          filters:
            branches:
              only: main